### ISSUE TITLE
Non working links

### ISSUE THREAD

**Issue by HuskyHunk** [bitsbb01/ustvgotom3u#1]
Channel urls are not working , none of the channels are working , looks like the mechanism is broken or changed to build the channel urls

**Comment by bitsbb01** [comment]
looking into it, as when i check ustvgo, its showing the correct channel urls, looks like the token isnt working right,, and they changed there player, so now theres a dead player link in all the pages, which doesnt lead anywhere,,, lol..   Give me a little bit, as also updatng the m3u creator,
